config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'search' => 'home#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'elasticsearch'

class HomeController < ApplicationController
  def home
  end

  def search
    client = Elasticsearch::Client.new log: false
    client.cluster.health
    client.transport.reload_connections!
    results = client.search q: params[:term]
    @page_results = results['hits']['hits']
    @total_hits = results['hits']['total']['value']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">S U C H E</h1>
  <p class="w3-xlarge">by Thorsten Claus</p>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag :term %>
    <%= submit_tag 'Search', class:"w3-button w3-black w3-padding-large w3-large w3-margin-top" %>
  <% end %>

</header>

app/views/home/search.html.erb
<div class="results">
<%= form_tag(search_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', class:"w3-button w3-black w3-padding-large w3-large w3-margin-top" %>
<% end %>

<hr>
Found: <%= @total_hits %> entries
<% @page_results.each do |target| %>
  <div class="card" style="width: 60rem;">
    <div class="card-body">
      <h5 class="card-title">
        <a href=<%= target["_source"]["url"] %> >
          <%= target["_source"]["title"] %>
        </a>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <a href=<%= target["_source"]["url"] %> class="card-link"><%= target["_source"]["url"] %>
        </a>
      </h6>
      <span class="card-text"><%= target["_source"]["description"] %></span>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
<meta charset="UTF-8">
<title>SearchConsole</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<body>

<div class="container">
<%= yield %>


<% if current_page?(root_path) %>
<% end %>

</div>
<!-- Footer -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>